version: '3.7'
services:
  php-fpm:
    working_dir: /app
    build:
      context: .
      target: php_dev
      dockerfile: ./docker-compose/php/Dockerfile
    volumes:
      - .:/app:cached
      - ./bin:/app/bin:consistent
      - ./config:/app/config:consistent
      - ./public:/app/public:consistent
      - ./src:/app/src:consistent
  nginx:
    build:
      context: .
      target: nginx_dev
      dockerfile: ./docker-compose/nginx/Dockerfile
    ports: ['8001:80']
    depends_on:
      - php-fpm
    volumes:
      - ./var/nginx/log:/var/log/nginx:cached
      - .:/app:cached
