version: '3.7'
services:
  php-fpm:
    working_dir: /var/www/html/symfony
    build:
      context: .
      target: php_dev
      dockerfile: ./docker-compose/php/Dockerfile
    volumes:
      - .:/var/www/html/symfony:cached
      - ./bin:/var/www/html/symfony/bin:consistent
      - ./config:/var/www/html/symfony/config:consistent
      - ./public:/var/www/html/symfony/public:consistent
      - ./src:/var/www/html/symfony/src:consistent
  nginx:
    build:
      context: .
      target: nginx_dev
      dockerfile: ./docker-compose/nginx/Dockerfile
    ports: ['8001:80']
    depends_on:
      - php-fpm
    volumes:
      - ./var/nginx/log:/var/log/nginx:cached
      - .:/var/www/html/symfony:cached
